version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27452:27452"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
    driver: local
